import java.util.HashSet;
//Let's create a HashSet that stores the student IDs of the students enrolled in the Java X course.
//The idea is to declare and initiate an emplty HashSet which e shall pppulate using the using teh add() method of teh Cooexn interface.

public class Students {
   public static void main(String[] args) {
   HashSet<integer>studentIDs = new HashSet<integer>();
    studentsIDs.add(23234);
    studentsIDs.add(12466);
    studentsIDs.add(02156);
    System.out.println("Student IDs:" + studentIDs);
//let's fetch some elements
    for(int id : student IDs) {
     System.out.println(id);
//we remove element using remove() method
     studentIDs.remove(23234);
     System.out.println("Updated Set:" + studentIDs);
    }
   }
 }
